/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create session request.
 * @export
 * @interface CreateSessionRequest
 */
export interface CreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    workDir?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof CreateSessionRequest
     */
    createDir?: boolean;
    /**
     * Per-session thinking override; null/undefined = use global config
     * @type {boolean}
     * @memberof CreateSessionRequest
     */
    thinking?: boolean | null;
    /**
     * Name of a discovered agent spec; null/undefined = use default agent
     * @type {string}
     * @memberof CreateSessionRequest
     */
    agentName?: string | null;
}

/**
 * Check if a given object implements the CreateSessionRequest interface.
 */
export function instanceOfCreateSessionRequest(value: object): value is CreateSessionRequest {
    return true;
}

export function CreateSessionRequestFromJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestFromJSONTyped(json, false);
}

export function CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workDir': json['work_dir'] == null ? undefined : json['work_dir'],
        'createDir': json['create_dir'] == null ? undefined : json['create_dir'],
        'thinking': json['thinking'] == null ? undefined : json['thinking'],
        'agentName': json['agent_name'] == null ? undefined : json['agent_name'],
    };
}

export function CreateSessionRequestToJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestToJSONTyped(json, false);
}

export function CreateSessionRequestToJSONTyped(value?: CreateSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'work_dir': value['workDir'],
        'create_dir': value['createDir'],
        'thinking': value['thinking'],
        'agent_name': value['agentName'],
    };
}

